name: addtimes
version: 0.1.0.0
synopsis: A small utility to sum up times inputed from stdin
description: See README.md
homepage: https://github.com/brcha/addtimes#readme
license: BSD3
author: Filip Brcic
maintainer: brcha@yandex.com
copyright: Copyright (c) 2021 Filip Brcic
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - time >= 1.8 && < 2

executables:
  addtimes:
    source-dirs: src
    main: Main.hs
